config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'
  get 'users/new'
  root 'sessions#new'
  get '/help' => 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout' => 'sessions#destroy'
  resources :users
  get '/show' => 'images#show'
  get '/new' => 'images#new'
  get '/test_cloudinary', to: 'test#cloudinary_test'
  
  get '/likedpage' => 'swipes#likedpage'
  get '/swipes' => 'swipes#index'
  get 'matches', to: 'swipes#matches'
  get 'swipes/:id/like', to: 'swipes#like', as: 'like_swipe'
  get 'swipes/:id/dislike', to: 'swipes#dislike', as: 'dislike_swipe'
  # resources :swipes do
  #   member do
  #     post :like
  #     post :dislike
  #   end
  # end
  
  get '/messages/:id' => 'messages#show', as: 'messages'
  post '/messages/:id' => 'messages#create'
  get '/inbox' => 'messages#inbox'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end 
  
  def contact
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h1>About</h1>
<p>The <a href="https://www.railstutorial.org/"><em>Ruby on Rails
Tutorial</em></a>, part of the
<a href="https://www.learnenough.com/">Learn Enough</a> family of
tutorials, is a
<a href="https://www.railstutorial.org/book">book</a> and
<a href="https://screencasts.railstutorial.org/">screencast series</a>
to teach web development with
<a href="https://rubyonrails.org/">Ruby on Rails</a>.
This is the sample app for the tutorial.
</p> 
</br>
<%= current_user.id %>
</br>


    

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>

<h1>Contact</h1>

<p>
    Contact the Ruby on Rails Tutorial about the sample app at the
    <a href="https://www.railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

<h1>Help</h1>


<%= form_with(model: @image, url: images_path, method: :post, local: true, multipart: true) do |form| %>
    <%= form.label :file, 'Choose Image' %>
    <%= form.file_field :file %>
    <%= form.submit 'Upload Image' %>
  <% end %>
  
  
<p>
    Get help on the Ruby on rails Tutorial at the 
    <a href="http://www.railstutorial.org">Rails Tutorials Help page</a>.
</p>
<a href="https://google.com"><em>Google </em></a>



<%= select_tag :options, options_for_select({ "Option 1" => "1", "Option 2" => "2", "Option 3" => "3" }) %>

<div> Price is: <p id="price">0</p></div>

<script>
    document.getElementById("options").addEventListener("change", event => {
        setPrice();
    });
    
    function setPrice()
    {
        var list = { "1": "10", "2": "20", "3": "30"};
        var price = list[document.getElementById("options").value];
        document.getElementById("price").innerHTML= price;
    }
    setPrice();
    
</script>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
    <h1>Sample App Amt</h1>
    
    <h2>
        This is the home page for my sample app. </br> </br>
        <a href="https://github.com/amtalucod">This is my link to my github account.</a>
        </br>
        
    </h2> 
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<img alt="Rails logo" width="200px" src="/assets/rails.png">