config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'
  get 'users/new'
  root 'sessions#new'
  get '/help' => 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout' => 'sessions#destroy'
  resources :users
  get '/show' => 'images#show'
  get '/new' => 'images#new'
  get '/test_cloudinary', to: 'test#cloudinary_test'
  
  get '/likedpage' => 'swipes#likedpage'
  get '/swipes' => 'swipes#index'
  get 'matches', to: 'swipes#matches'
  get 'swipes/:id/like', to: 'swipes#like', as: 'like_swipe'
  get 'swipes/:id/dislike', to: 'swipes#dislike', as: 'dislike_swipe'
  # resources :swipes do
  #   member do
  #     post :like
  #     post :dislike
  #   end
  # end
  
  get '/messages/:id' => 'messages#show', as: 'messages'
  post '/messages/:id' => 'messages#create'
  get '/inbox' => 'messages#inbox'
end

app/models/user.rb
class User < ApplicationRecord
    has_many :images, dependent: :destroy
    accepts_nested_attributes_for :images
    
    belongs_to :location
    accepts_nested_attributes_for :location 
    
    has_many :swipes, dependent: :destroy
    has_many :liked_swipes, class_name: 'Swipe', foreign_key: 'user_id', dependent: :destroy
    has_many :disliked_swipes, class_name: 'Swipe', foreign_key: 'user_id', dependent: :destroy
    
    has_many :sent_messages, class_name: 'Message'
    has_many :received_messages, class_name: 'Message'
    
    
    before_save { self.email = email.downcase }
    validates :first_name, presence: true, length: { maximum: 50 }
    validates :last_name, presence: true, length: { maximum: 50 }
    validates :mobile_number, presence: true, length: { minimum: 11, maximum: 15 }, uniqueness: true,
                    format: { with: /\A[\d\+]+\z/, message: "only allows numerical digits" }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
    validates :birthdate, presence: true     
    validates :gender, presence: true  
    validates :sexual_orientation, presence: true             
    validates :gender_interest, presence: true  
    validates :bio, presence: true, length: { maximum: 300 }  
      has_secure_password     
     validates :password, presence: true, length: { minimum: 6 }, allow_nil: true           
    
    validate :validate_photo_count, on: :create
    private
    def validate_photo_count
        splitted_photos = photos.split(",").length
        final_count = (splitted_photos - 1) / 4
        if final_count < 1
        errors.add(:base, "At least one photo is required")
        elsif final_count > 5
        errors.add(:base, "Maximum of 5 photos allowed")
        end
    end

    # Returns the hash digest of the given string.
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
                                                    BCrypt::Password.create(string, cost: cost)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index]
  before_action :correct_user, only: [:edit, :update, :destroy, :show]
  before_action :admin_user, only: [:index, :destroy]
  
  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
    @images = Image.where(user: current_user)
              .order(:created_at)
              
    liked_swipes = @user.swipes.where(liked: true)
    liked_swipes = liked_swipes.where(liked_user_id: User.pluck(:id)) #remove deleted users from liked swipes object
    
    matched_swipes = liked_swipes.select do |swipe|
      @user.swipes.exists?(liked_user_id: swipe.user_id, liked: true) &&
        swipe.liked_user.swipes.exists?(liked_user_id: @user.id, liked: true)
    end

      @matches = matched_swipes.reject { |swipe| swipe.liked_user_id == @user.id }.map(&:liked_user)
      @images = @matches.map(&:images)
              
  end
    
  def new
    @user = User.new
    @user.build_location
    
  end
  
  def create
    @user = User.new(user_params) 
    if @user.save
      
      if params[:user][:photos].present?
        params[:user][:photos].each do |image|
          if image != ""
            Rails.logger.error("Print mo tempfile: #{image.tempfile}")
           cloudinary_upload = Cloudinary::Uploader.upload(image.tempfile)
           @img = @user.images.build(user: @user, cloudinary_url: cloudinary_upload['secure_url'])
            if !@img.save
              @img.errors.full_messages.each do |msg|
                Rails.logger.error("Failed to save image: #{msg}")
              end
            else
             Rails.logger.error("Uploaded: #{cloudinary_upload['secure_url']}")
            end
          end
        end
      end
    
      log_in @user
      flash[:notice] = "Welcome, User successfully created !"
      redirect_to @user
    else
      @user.errors.full_messages.each do |msg|
        Rails.logger.error("Failed to save user: #{msg}")
      end
      flash.now[:notice] = "Error creating user. Please fix the following errors:"
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
    @user.build_location if @user.location.nil?
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "Profile updated"
      redirect_to @user
    else
      flash[:notice] = "Error"
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:notice] = "User deleted"
    redirect_to users_path
  end
    
  private
    def user_params
      params.require(:user).permit(:email, :password, 
                              :password_confirmation, :first_name, :last_name, :mobile_number,
                              :birthdate, :gender, :sexual_orientation, :gender_interest,
                              :school, :bio, photos: [], :location_attributes => [:country, :state_region, :city])
    end
    
    # Before filters
    
    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:notice] = "Please log in."
        redirect_to login_path
      end
    end
    
    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
  
      unless current_user?(@user) || current_user.admin?
        flash[:notice] = "Not Authorized."
        redirect_to swipes_path
      end
    end
  
  
    #Confirms an admin user.
    def admin_user
      if current_user.nil? || !current_user.admin?
        flash[:notice] = "Not Authorized."
        redirect_to swipes_path
      end
    end
  end

app/helpers/users_helper.rb
module UsersHelper
    # Returns the Gravatar for the given user.
    
end

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>

<% provide(:title, "Edit user") %>
<div class="card">
  <h5 class="card-header">Edit User</h5>
    <div class="card-body">
    <%= form_for(@user) do |f| %>
      <% if @user.errors.any? %>
          <div style="color: red">
            <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
            <ul>
              <% @user.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
      <div class="field form-group">
          <%= f.label :first_name %><br />
          <%= f.text_field :first_name, autofocus: true, autocomplete: "first-name", class:"form-control", placeholder:"First Name" %>
      </div><br />
      
      <div class="field form-group">
          <%= f.label :last_name %><br />
          <%= f.text_field :last_name, autofocus: true, autocomplete: "last-name", class:"form-control", placeholder:"Last Name" %>
      </div><br />
      
      <div class="field form-group">
        <%= f.label :mobile_number %><br />
        <%= f.text_field :mobile_number, autofocus: true, autocomplete: "mobile-number", class:"form-control", placeholder:"Mobile Number" %>
      </div><br />
        
      <div class="field form-group">
        <%= f.label :email %><br />
        <%= f.email_field :email, autofocus: true, autocomplete: "email", class:"form-control", placeholder:"Email" %>
      </div><br />
      
      <div class="field form-group">
          <%= f.label :birthdate %><br />
          <%= f.date_field :birthdate, autofocus: true, autocomplete: "birthdate", class:"form-control", placeholder:"Birthdate" %>
      </div><br />
      
      <div class="field form-group">
        <%= f.label :gender %><br />
        <%= f.select :gender, [['Male', 'male'], ['Female', 'female'], ['Non-binary', 'non-binary'], ['Genderqueer', 'genderqueer'], ['Genderfluid', 'genderfluid'], 
        ['Agender', 'agender'], ['Bigender', 'bigender'], ['Two-Spirit', 'two-spirit'], ['Transgender', 'transgender'], ['Gender nonconforming', 'gender nonconforming']], { prompt: 'Select gender' }, class: "form-control" %>
      </div>
      
      <br/>
      <div class="field form-group">
        <%= f.label :sexual_orientation %><br />
        <%= f.select :sexual_orientation, [['Heterosexual (Straight)', 'heterosexual (Straight)'], ['Homosexual (Gay/Lesbian)', 'homosexual (Gay/Lesbian)'],
                      ['Bisexual', 'bisexual'], ['Pansexual', 'pansexual'], ['Asexual', 'asexual'], ['Demisexual', 'demisexual'], ['Queer', 'queer'],
                      ['Questioning', 'questioning'], ['Polysexual', 'polysexual'], ['Androsexual/Gynesexual', 'androsexual/gynesexual']],  { prompt: 'Select sexual-orientation' }, class: "form-control" %>
      </div><br/>
      
      <div class="field form-group">
        <%= f.label :gender_interest %><br />
        <%= f.select :gender_interest, [['Male', 'male'], ['Female', 'female'], ['Non-binary', 'non-binary'], ['Genderqueer', 'genderqueer'], ['Genderfluid', 'genderfluid'], 
                      ['Agender', 'agender'], ['Bigender', 'bigender'], ['Two-Spirit', 'two-spirit'], ['Transgender', 'transgender'], ['Gender nonconforming', 'gender nonconforming']], { prompt: 'Select gender' }, class: "form-control" %>
      </div>
      <br/>
      
      <%= f.fields_for :location, @user.location || @user.build_location do |l| %>
        <%= l.label :country %>
        <%= l.text_field :country, autofocus: true, autocomplete: "country", class: "form-control", placeholder: "Country" %>
        <br />
        <%= l.label :state_region %>
        <%= l.text_field :state_region, class: "form-control", placeholder: "State/Region" %>
        <br />
        <%= l.label :city %>
        <%= l.text_field :city, class: "form-control", placeholder: "City" %>
        <br />
      <% end %>
      
      <div class="field form-group">
        <%= f.label :school %><br />
        <%= f.text_field :school, autofocus: true, autocomplete: "school", class: "form-control", placeholder: "School" %><br />
      </div>

      <div class="field form-group">
        <%= f.label :bio %><br />
        <%= f.text_area :bio, autofocus: true, autocomplete: "bio", class: "form-control", placeholder: "Bio" %><br />
      </div>
    
      <div class="field form-group">
        <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
        <%= f.password_field :password, autocomplete: "new-password", class:"form-control", placeholder:"6 characters minimum" %>
        <% if @minimum_password_length %>
        <% end %>
      </div><br />
    
      <div class="field form-group">
        <%= f.label :password_confirmation %><br />
        <%= f.password_field :password_confirmation, autocomplete: "new-password", class:"form-control", placeholder:"6 characters minimum" %>
      </div>
      </br>
      <div class="field form-group">
        <% f.label :current_password %> <br />
        <% f.password_field :current_password, autocomplete: "current-password", class:"form-control", placeholder:" " %>
      </div>
      <div class="actions">
        <%= f.submit "Update", class:"btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>
</br>
<div class="card">
  <h5 class="card-header">Cancel my account</h5>
  <div class="card-body">
  <div>Unhappy? <%= button_to "Cancel my account", current_user, data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, method: :delete, class:"btn btn-danger btn-sm" %></div>
    </br>
    
  </div>
</div>

<script>
    document.addEventListener("click", event => {
        const element = event.target.closest("[data-confirm]")

        if (element && !confirm(element.dataset.confirm)) {
            event.preventDefault()
        }
    })
</script>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<br />
<h1>All users</h1>
<div class="container">
  <div class="center-container" style="display: ruby-text;">
<table class="table table-hover table-bordered">
    <thead class="table-danger" style="text-align: center">
      <tr>
        <th style="width: 10%;">Photo</th>
        <th style="width: 20%;">First Name</th>
        <th style="width: 20%;">Last Name</th>
        <th style="width: 17%;">View</th>
        <th style="width: 17%;">Edit</th>
        <th style="width: 16%;">Delete</th>
      </tr>
    </thead>
    <tbody style="text-align: center; vertical-align: middle;">
      <% @users.each do |user| %>
        <% unless user.admin? %>
          <tr>
            <td><%= image_tag user.images[0].cloudinary_url, style: "width: 50px; height: 70px; object-fit: cover;" %></td>
            <td><%= user.first_name %></td>
            <td><%= user.last_name %></td>
            <td><%= link_to "View", user_path(user) %></td>
            <td><%= link_to "Edit", edit_user_path(user) %></td>
            <td><%= button_to "Delete", user, method: :delete,
                                      data: { confirm: "You sure?" }  %></td>
        <% end %>
      <% end %>
    </tbody>
</table>
</div>
</div>



<script>
    document.addEventListener("click", event => {
        const element = event.target.closest("[data-confirm]")

        if (element && !confirm(element.dataset.confirm)) {
            event.preventDefault()
        }
    })
</script>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div class="card">
  <h5 class="card-header">Sign up</h5>
    <div class="card-body">
      <%= form_with(model: @user, local: true, html: { multipart: true }) do |f| %>
        
        <% if @user.errors.any? %>
          <div style="color: red">
            <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

            <ul>
              <% @user.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        
        
        <div class="field form-group">
          <% f.label :first_name %><br />
          <%= f.text_field :first_name, autofocus: true, autocomplete: "first-name", class:"form-control", placeholder:"First Name" %>
        </div>
        
        <div class="field form-group">
          <% f.label :last_name %><br />
          <%= f.text_field :last_name, autofocus: true, autocomplete: "last-name", class:"form-control", placeholder:"Last Name" %>
        </div>
        
        <div class="field form-group">
          <% f.label :mobile_number %><br />
          <%= f.text_field :mobile_number, autofocus: true, autocomplete: "mobile-number", class:"form-control", placeholder:"Mobile Number" %>
        </div>
        
        <div class="field form-group">
          <% f.label :email %><br />
          <%= f.email_field :email, autofocus: true, autocomplete: "email", class:"form-control", placeholder:"Email" %>
        </div></br>
        
        <div class="field form-group">
          <%= f.label :birthdate %><br />
          <%= f.date_field :birthdate, autofocus: true, autocomplete: "birthdate", class:"form-control", placeholder:"Birthdate" %>
        </div>
        
        <br/>
        <div class="field form-group">
          <%= f.label :gender %><br />
          <%= f.select :gender, [['Male', 'male'], ['Female', 'female'], ['Non-binary', 'non-binary'], ['Genderqueer', 'genderqueer'], ['Genderfluid', 'genderfluid'], 
          ['Agender', 'agender'], ['Bigender', 'bigender'], ['Two-Spirit', 'two-spirit'], ['Transgender', 'transgender'], ['Gender nonconforming', 'gender nonconforming']], { prompt: 'Select gender' }, class: "form-control" %>
        </div>
        
        <br/>
        <div class="field form-group">
          <%= f.label :sexual_orientation %><br />
          <%= f.select :sexual_orientation, [['Heterosexual (Straight)', 'heterosexual (Straight)'], ['Homosexual (Gay/Lesbian)', 'homosexual (Gay/Lesbian)'],
                        ['Bisexual', 'bisexual'], ['Pansexual', 'pansexual'], ['Asexual', 'asexual'], ['Demisexual', 'demisexual'], ['Queer', 'queer'],
                        ['Questioning', 'questioning'], ['Polysexual', 'polysexual'], ['Androsexual/Gynesexual', 'androsexual/gynesexual']],  { prompt: 'Select sexual-orientation' }, class: "form-control" %>
        </div><br/>
        
        <div class="field form-group">
          <%= f.label :gender_interest %><br />
          <%= f.select :gender_interest, [['Male', 'male'], ['Female', 'female'], ['Non-binary', 'non-binary'], ['Genderqueer', 'genderqueer'], ['Genderfluid', 'genderfluid'], 
                        ['Agender', 'agender'], ['Bigender', 'bigender'], ['Two-Spirit', 'two-spirit'], ['Transgender', 'transgender'], ['Gender nonconforming', 'gender nonconforming']], { prompt: 'Select gender' }, class: "form-control" %>
        </div>
        <br/>
        
        <%= f.fields_for :location_attributes do |l| %>
        <%#= f.fields_for :location, resource.location || resource.build_location do |l| %>
          <%= l.label :country %>
          <%= l.text_field :country, autofocus: true, autocomplete: "country", class: "form-control", placeholder: "Country" %>
          
          <%= l.label :state_region %>
          <%= l.text_field :state_region, class: "form-control", placeholder: "State/Region" %>
          
          <%= l.label :city %>
          <%= l.text_field :city, class: "form-control", placeholder: "City" %>
        <% end %>
        
        

        <div class="field form-group"><br />
          <% f.label :school %>
          <%= f.text_field :school, autofocus: true, autocomplete: "school", class: "form-control", placeholder: "School" %><br />
        </div>

        <div class="field form-group">
          <% f.label :bio %>
          <%= f.text_area :bio, autofocus: true, autocomplete: "bio", class: "form-control", placeholder: "Bio" %><br />
        </div>
               
        <div class="field form-group">
          <% f.label :password %>
          <% if @minimum_password_length %>
          
          <% end %>
          <%= f.password_field :password, autocomplete: "new-password", class:"form-control", placeholder:"Password (6 characters minimum)" %>
        </div>
      
        <div class="field form-group">
          <% f.label :password_confirmation %><br />
          <%= f.password_field :password_confirmation, autocomplete: "new-password", class:"form-control", placeholder:"Password Confirmation" %>
        </div><br/>
        
        <div class="field">
          <%= f.label :photos, "Profile Image (1 photo required, 5 photos max)" %> <br/>
          <%= f.file_field :photos, multiple: true %>
        </div>
        
        </br>
        <div class="actions">
          <%= f.submit "Sign up", class:"btn btn-success" %>
        </div>
        
      <% end %>
    </br>
    
  
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "Profile") %>

</br>
<div class="container bg-danger-subtle" >
  <div class="row">
    <div class="col-md-10">
      <div class="jumbotron">
      <div class="d-flex flex-column">
        <%#= image_tag @user.images[0].cloudinary_url, class: "img-thumbnail align-self-start", alt: "Image 1", data: { bs_toggle: "modal", bs_target: "#imageModal" }%>
        
        <% if @user.images[0].present? %>
          <%= image_tag @user.images[0].cloudinary_url, class: "img-thumbnail align-self-start", alt: "Image 1", data: { bs_toggle: "modal", bs_target: "#imageModal"}, style: "width: 300px; height: 400px; object-fit: cover;" %>
        <% end %>
        
        <%# if @images[0].present? %>
          <%#= image_tag @images[0].cloudinary_url, class: "img-thumbnail align-self-start", alt: "Image 1", data: { bs_toggle: "modal", bs_target: "#imageModal" } %>
        <%# else %>
          <!-- Handle case when images are nil or empty -->
          <%#= image_tag "", class: "img-thumbnail align-self-start", alt: "Default Image", data: { bs_toggle: "modal", bs_target: "#imageModal" } %>
        <%# end %>
        
        <%= button_tag "Show Photo Gallery", type: "button", class: "btn btn-primary align-self-start", data: { bs_toggle: "modal", bs_target: "#imageModal" } %>
      </div>
      
        <h3 class="display-4"><%= "#{@user.first_name} #{@user.last_name}"  %></h3>
        <p class="lead"><%= @user.location&.city %> | <%= @user.location&.state_region %> | <%= @user.location&.country %></p>
        <hr class="my-4">
        <p><%= @user.bio %></p>
        </br>
        
        <% if current_user.admin? %>
          <h4>"My Matches"</h5>
          <% if @matches.present? %>
              <% @matches.each do |matched_user| %>
                    <div class="card matches-card">
                      <div>
                        <%= image_tag matched_user.images[0].cloudinary_url, height: "150px", width: "159px", style: "object-fit: cover;", class: "card-img-top" %>
                        <div class="card-body">
                          <h6><p class="card-text"><%= matched_user&.first_name %> <%= matched_user&.last_name %></p></h6>
                          <%= button_to "Message Me", messages_path(matched_user), method: :get, class: "btn btn-primary" %>
                        </div>
                      </div>
                  </div>
              <% end %>
          <% else %>
            <div class="container">
              <div class="row justify-content-center">
                <div class="col-md-6">
                  <div class="card">
                    <div class="card-body text-center">
                      <h3>No matches yet.</h3>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
         <% end %> 
        </br>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="imageModal" tabindex="-1" aria-labelledby="imageModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="imageModalLabel">Photo Gallery</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <% @user.images.each do |image| %>
          <%= image_tag image.cloudinary_url, class: "img-fluid", id: "modalImage", alt: "Image", style: "width: 250px; height: 300px; object-fit: cover;" %>
        <% end %>  
      </div>
    </div>
  </div>
</div>


<script>
  // Script to display clicked image in modal
  document.querySelectorAll('.img-thumbnail').forEach(item => {
    item.addEventListener('click', event => {
      const imgSrc = event.target.src;
      document.getElementById('modalImage').src = imgSrc;
    });
  });
</script>






          