config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'
  get 'users/new'
  root 'sessions#new'
  get '/help' => 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout' => 'sessions#destroy'
  resources :users
  get '/show' => 'images#show'
  get '/new' => 'images#new'
  get '/test_cloudinary', to: 'test#cloudinary_test'
  
  get '/likedpage' => 'swipes#likedpage'
  get '/swipes' => 'swipes#index'
  get 'matches', to: 'swipes#matches'
  get 'swipes/:id/like', to: 'swipes#like', as: 'like_swipe'
  get 'swipes/:id/dislike', to: 'swipes#dislike', as: 'dislike_swipe'
  # resources :swipes do
  #   member do
  #     post :like
  #     post :dislike
  #   end
  # end
  
  get '/messages/:id' => 'messages#show', as: 'messages'
  post '/messages/:id' => 'messages#create'
  get '/inbox' => 'messages#inbox'
end

app/models/swipe.rb
class Swipe < ApplicationRecord
    belongs_to :user
    belongs_to :liked_user, class_name: 'User', foreign_key: 'liked_user_id', optional: true
    belongs_to :disliked_user, class_name: 'User', foreign_key: 'disliked_user_id', optional: true

    has_many :messages, dependent: :destroy
    
    
end

app/controllers/swipes_controller.rb
class SwipesController < ApplicationController
  before_action :logged_in_user, only: [:index, :matches, :likedpage]
  before_action :admin_user, only: [:likedpage]
  
    def index
      liked_user_ids = current_user.liked_swipes.pluck(:liked_user_id)
      disliked_user_ids = current_user.disliked_swipes.pluck(:disliked_user_id)
      @users = User.where(gender: current_user.gender_interest)
                              .where.not(id: current_user.id)
                              .where.not(id: liked_user_ids)
                              .where.not(id: disliked_user_ids) 
      # Use map to iterate over each user in @users, For each user, we access their images using user.images.
      @images = @users.map(&:images)
    end
    
    def likedpage
      @users = User.all
      @matches = []
      
      @users.each do |user|
        @swipes = user.swipes.all
      liked_swipes = user.swipes.where(liked: true)
  
      # Find match
      matched_user_ids = liked_swipes.select do |swipe|
        user.swipes.exists?(liked_user_id: swipe.user_id, liked: true)
      end.pluck(:user_id)
      
      # Group the swipes by liked_user_id and count the number of swipes for each user
      matched_user_counts = liked_swipes.group(:liked_user_id).count
      
      # Retrieve matched + count
      @indv_matches = User.where(id: matched_user_ids)
              .includes(:images)
              .map { |user| { user: user, match_count: matched_user_counts[user.id] || 0 } }
      
      # Add indv match to match array
      @matches.concat(@indv_matches)
      end
      
      # Add users no match 
        users_without_matches = User.where.not(id: @matches.map { |match| match[:user].id })
        .includes(:images)
        .map { |user| { user: user, match_count: 0 } }
      @matches.concat(users_without_matches)
      
    end
    
    def matches
      liked_swipes = current_user.swipes.where(liked: true)
      liked_swipes = liked_swipes.where(liked_user_id: User.pluck(:id)) #remove deleted users from liked swipes object
      # matched_swipes = liked_swipes.select do |swipe|
      #   current_user.swipes.exists?(liked_user_id: swipe.user_id, liked: true)
      # end
      #Rails.logger.error("Alfred")
      #Rails.logger.error(liked_swipes)
      matched_swipes = liked_swipes.select do |swipe|
        current_user.swipes.exists?(liked_user_id: swipe.user_id, liked: true) &&
          #swipe.user.swipes.exists?(liked_user_id: current_user.id, liked: true)
          swipe.liked_user.swipes.exists?(liked_user_id: current_user.id, liked: true)
      end

       @matches = matched_swipes.reject { |swipe| swipe.liked_user_id == current_user.id }.map(&:liked_user)
       @images = @matches.map(&:images)
    end  
      #@matches = matched_swipes.map(&:liked_user).compact
      #@images = @matches.map { |user| user.images if user }.compact
      
      #matched_user_counts = liked_swipes.group(:liked_user_id).count
    
    
    
    
    def like
      user = User.find(params[:id])
      current_user.swipes.create(liked_user: user, liked: true)
      
      # Check if liked user also liked current_user
      if Swipe.exists?(user_id: user.id, liked_user_id: current_user.id, liked: true)
      # Both users have liked = match
        current_user.swipes.create(user_id: user.id, liked_user_id: current_user.id, liked: true, matched: true)
        user.swipes.create(user_id: current_user.id, liked_user_id: user.id, liked: true, matched: true)
      end
    
      #redirect_to swipes_path
      render json: { message: 'success' }
    end
    
    def dislike
      user = User.find(params[:id])
      current_user.swipes.create(disliked_user: user, liked: false)
      #redirect_to swipes_path
      render json: { message: 'success' }
    end
    
    private
    
      def logged_in_user
        unless logged_in?
          store_location
          flash[:notice] = "Please log in."
          redirect_to login_path
        end
      end
      
      def admin_user
        if current_user.nil? || !current_user.admin?
          flash[:notice] = "Not Authorized."
          redirect_to swipes_path
        end
      end
end

app/views/swipes/likedpage.html.erb
<% provide(:title, "All Matches") %>
<br/>
<h1>All Matches</h1>
<div class="container">
  <div class="center-container" style="display: ruby-text;">
    <table class="table table-hover table-bordered" style="width: 80%;">
        <thead class="table-danger" style="text-align: center">
          <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Matches</th>
          </tr>
        </thead>
        <tbody style="text-align: center; vertical-align: middle;">
            <% @matches.each do |matched_user| %>
              <% unless matched_user[:user].admin? %>
              
              <tr>
                <td><%= matched_user[:user]['first_name'] %></td>
                <td><%= matched_user[:user]['last_name'] %></td>
                <td><%= matched_user[:match_count] %></td>
              <% end %>
          <% end %>
        </tbody>
    </table>
  </div>
</div>

app/views/swipes/matches.html.erb
<% provide(:title, "Matches") %>
<h1>Your Matches</h1>

<% if @matches.present? %>
    <% @matches.each do |matched_user| %>
          <div class="card matches-card">
            <div>
              <%= image_tag matched_user.images[0].cloudinary_url, height: "150px", width: "159px", style: "object-fit: cover;", class: "card-img-top" %>
              <div class="card-body">
                <h6><p class="card-text"><%= matched_user&.first_name %> <%= matched_user&.last_name %></p></h6>
                <%= button_to "Message Me", messages_path(matched_user), method: :get, class: "btn btn-primary" %>
              </div>
            </div>
        </div>
    <% end %>
<% else %>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card">
          <div class="card-body text-center">
            <h3>No matches yet.</h3>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

 

app/views/swipes/test.html.erb
<% provide(:title,'') %>
<br />
<% if @users.any? %>
<% user = @users.first %>
  <div class="d-flex justify-content-center">
    <div class="card" style="width: 25rem;">
      <div class="d-flex justify-content-center ">
        <%= image_tag user.images[0].cloudinary_url, class: "img-thumbnail card-img-top", alt: "Image 1", data: { bs_toggle: "modal", bs_target: "#imageModal" }, style: "width: 400px; height: 400px; object-fit: cover;" %>
      </div>
      <div class="d-flex justify-content-center ">
        <%= button_tag "Show Photo Gallery", type: "button", class: "btn btn-secondary align-self-start btn-sm", data: { bs_toggle: "modal", bs_target: "#imageModal" } %>
      </div>
        <div class="card-body">
          <div class="d-flex justify-content-center">
            <div class="col-md-6">
              <%= button_to "Dislike", dislike_swipe_path(user), method: :post, class: "btn btn-danger btn-lg", style: "width: 170px;" %>
            </div>
            <div class="col-md-6">
              <%= button_to "Like", like_swipe_path(user), method: :post, class: "btn btn-primary btn-lg", style: "width: 170px;" %>
            </div> 
          </div>
          <h4 class="card-title"><%= user.first_name %> <%= user.last_name %></h4>
          <h7><%= user.location.country %> | <%= user.location.state_region %> | <%= user.location.city %> </h7>
            <textarea class="form-control" rows="3" readonly><%= "Bio:\n#{user.bio}" %></textarea> <!-- Used a textarea for the bio -->
            <!-- Modal -->
            <div class="modal fade" id="imageModal" tabindex="-1" aria-labelledby="imageModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-lg">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="imageModalLabel">Photo Gallery</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    <% user.images.each do |image| %>
                      <%= image_tag image.cloudinary_url, class: "img-fluid", id: "modalImage", alt: "Image", style: "width: 250px; height: 300px; object-fit: cover;" %>
                    <% end %>  
                  </div>
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
  <% else %>
    <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card">
          <div class="card-body text-center">
            <h3>No more profiles to show.</h3>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

<script>
  // Script to display clicked image in modal
  document.querySelectorAll('.img-thumbnail').forEach(item => {
    item.addEventListener('click', event => {
      const imgSrc = event.target.src;
      document.getElementById('modalImage').src = imgSrc;
    });
  });
</script>