config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'
  get 'users/new'
  root 'sessions#new'
  get '/help' => 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout' => 'sessions#destroy'
  resources :users
  get '/show' => 'images#show'
  get '/new' => 'images#new'
  get '/test_cloudinary', to: 'test#cloudinary_test'
  
  get '/likedpage' => 'swipes#likedpage'
  get '/swipes' => 'swipes#index'
  get 'matches', to: 'swipes#matches'
  get 'swipes/:id/like', to: 'swipes#like', as: 'like_swipe'
  get 'swipes/:id/dislike', to: 'swipes#dislike', as: 'dislike_swipe'
  # resources :swipes do
  #   member do
  #     post :like
  #     post :dislike
  #   end
  # end
  
  get '/messages/:id' => 'messages#show', as: 'messages'
  post '/messages/:id' => 'messages#create'
  get '/inbox' => 'messages#inbox'
end

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= notice  %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        <a href="https://www.railstutorial.org/">Ruby on Rails</a>
        
    </small>
    <nav>
        <ul>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
            <li><a href="https://news.railstutorial.org/">News</a></li>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg" style="background-color: #ff69b4;">
  <div class="container-fluid">
    <% if logged_in? && current_user.admin? %>
      <%= link_to 'Dating App', users_path, class: "navbar-brand" %>
    <% elsif logged_in? %>
      <%= link_to 'Dating App', swipes_path, class: "navbar-brand" %>
    <% else %>
      <%= link_to 'Dating App', login_path, class: "navbar-brand" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent", style= "flex-grow: 0;">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      
        <% if logged_in? && current_user.admin? %>
          <li class="nav-item">
            <%= link_to 'Users Manager', users_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Matches Manages', likedpage_path, class:"nav-link" %>
          </li>
        <% end %>
        
        <% if logged_in? && !current_user.admin? %>  
          <li class="nav-item">
            <%= link_to 'Swipe Page', swipes_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Matches', matches_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%#= link_to 'Inbox', inbox_path, class:"nav-link" %>
          </li>
        <% end %>
        
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Settings
            </a>
            <ul class="dropdown-menu">
              <li class="nav-item">
              <%= link_to 'Profile', current_user, class: "nav-link dropdown-item"%>
              </li>
              
              <li class="nav-item">
               <%= link_to 'Edit Profile', edit_user_path(current_user), class: "nav-link dropdown-item"%>
              </li>
              <li><hr class="dropdown-divider"></li>
              <li class="nav-item">
               <%= link_to 'Log Out', logout_path, method: :delete, class: "nav-link dropdown-item" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Log in', login_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Up', signup_path, class:"nav-link" %>
          </li>
        <% end %>
      </ul>
   
    

    </div>
  </div>
</nav>

app/views/layouts/_rails_default.html.erb
<meta name="viewport" content="width=device-width,initial-scale=1">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<%= javascript_importmap_tags %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
  <title><%= full_title(yield(:title)) %></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= favicon_link_tag 'favicon.ico' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>   
  </head>
  <body>
    <%= render 'layouts/header' %>
    
    <div class="container">
    
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      
      
      
      <%= yield %>
      
      <%= debug(params) if Rails.env.development? %>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" ></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

  </body>
</html>